server:
  port: 8081

services:
  client-info-service-port: 8083
  bank-info-service-port: 8082

spring:
  data:
    mongodb:
      database: test

service:
  withdrawal:
    account-credit-limit: 5000 # User can't withdraw money having 5000$ debt on their account